### ISSUE TITLE
FPS problem

### ISSUE THREAD

**Issue by yyeerai** [BloodWorkXGaming/ExNihiloCreatio#52] opened 2017-12-22 05:14 UTC
FPS decreased to 0 when infected with leaves

**Comment by BloodWorkXGaming** [comment] 2017-12-22 08:30
This is already fixed in dev and should be much better next version

yyeerai <notifications@github.com> schrieb am Fr., 22. Dez. 2017, 06:14:

**Comment by SirLyle** [comment] 2017-12-23 16:27
Duplicate of Issue #33.

**Closed as completed** 2018-01-22 00:43 UTC
Labels: bug, duplicate
