### ISSUE TITLE
cant craft ore pieces to ore chunks

### ISSUE THREAD

**Issue by aussie4** [BloodWorkXGaming/ExNihiloCreatio#251] opened 2019-07-11 02:05 UTC
Added ExNihiloCreatio and ex Compression to skyfactory 4. using exNihiloCreatio 0.4.5.1, I cant craft ore chunks from the ore pieces. Did something change with the crafting or is there an error?

**Comment by SirLyle** [comment] 2019-07-11 04:15
Nothing has changed for Ex Nihilo Creatio's recipes; looking at SF4 it appears they have some complicated custom crafttweaker scripts; some of which seems to be intended for "unify"ing. I would guess somewhere in that pile of scripts they are clearing existing recipes. You might have better luck asking the SF4 devs if they do any recipe clearing of oredict entries.

I would suggest manually adding the recipes back with crafttweaker to avoid breaking any of the pack.

If no one reports this issue occurring in packs without such scripting I will close this issue as not a bug.

**Comment by aussie4** [comment] 2019-07-11 21:48
Went to their github and got no help

**Comment by SirLyle** [comment] 2019-07-11 21:59
Well I can't fix it on my end so I suggest you edit the crafttweaker scripts to re-add the recipes, *after* all the SF4 scripts run.

**Comment by SirLyle** [comment] 2019-08-05 22:24
Closing as this isn't an issue with ex nihilo and is a result of the craft tweaker scripts.

**Closed as completed by SirLyle** 2019-08-05 22:24 UTC
