### ISSUE TITLE
Crashreport generated by VanillaFix

### ISSUE THREAD

**Issue by ghost** [BloodWorkXGaming/ExNihiloCreatio#163] opened 2019-02-13 08:24 UTC
https://paste.dimdev.org/suyopacuti.mccrash

**Comment by SirLyle** [comment] 2019-02-13 23:20
Got any context for this? What were you doing?

Please update your Ex Nihilo Creatio install (the current version is 0.3.7) and see if the error persists.

**Comment by ghost** [comment] 2019-02-14 06:13
All I know is that I have three wooden Barrels generating dirt using hoppers to feed them rotten flesh. I also have some iron sieves standing around. I don’t have anymore Information, except it might be possible that the error appeared right as I was walking outside of chunk loaded chunks. I still was near my skyblock base, so i think i shouldn’t have unloaded them (only like 30 blocks away). Otherwise I can’t say you more, as the error appeared completley out of nowhere (ah yes, as it appeared it started lagging really badly), but restarting not only my world, but minecraft seemed to solve the Problem.
Updating I propably will do, allthough I’m playing a modpack and I rather just update that to avoid Bugs. 

Anyway, thank you for trying to help me.
Von: SirLyle
Gesendet: Donnerstag, 14. Februar 2019 00:20
An: BloodyMods/ExNihiloCreatio
Cc: lizardluis; Author
Betreff: Re: [BloodyMods/ExNihiloCreatio] Crashreport generated by VanillaFix(#163)

Got any context for this? What were you doing?
Please update your Ex Nihilo Creatio install (the current version is 0.3.7) and see if the error persists.

**Comment by SirLyle** [comment] 2019-02-15 04:41
Was this while playing on a server? If so do you have a server log?

**Comment by SirLyle** [comment] 2019-02-15 04:45
I think it might be a desync due to being outside the render range and not receiving the packet that changes the barrel mode. I can (through convoluted redstone) get log spam with a similar error, but can't get a crash.

**Comment by ghost** [comment] 2019-02-15 07:05
It isn’t on a Server, also i haven’t been recieving the error message sience it first appeared. VanillaFix actually didn’t say it caused a crash, rather it said that «this didn’t cause a crash, but will likely result in world corruption or other Problems in the future», or something like that. Sience it isn’t a crash, I do not have anymore Information.
Von: SirLyle
Gesendet: Freitag, 15. Februar 2019 05:45
An: BloodyMods/ExNihiloCreatio
Cc: lizardluis; Author
Betreff: Re: [BloodyMods/ExNihiloCreatio] Crashreport generated by VanillaFix(#163)

I think it might be a desync due to being outside the render range and not receiving the packet that changes the barrel mode. I can (through convoluted redstone) get log spam with a similar error, but can't get a crash.

**Comment by SirLyle** [comment] 2019-02-16 04:25
A fix has been merged. I believe it was caused by the barrel changing modes while the user is outside the tile entity render range, but within the chunk loading distance, so there is a client/server desync which makes the client have NPEs on subsequent updates.

**Closed as completed by SirLyle** 2019-02-16 04:25 UTC
Labels: bug, Need More Information
