### ISSUE TITLE
вылет игра как только она запускается 

### ISSUE THREAD

**Issue by KiraLinux** [BloodWorkXGaming/ExNihiloCreatio#150] opened 2019-02-02 18:26 UTC
загружается и вылетает как только коснется загрузка Forgelin

вот журнал событий 
https://gist.github.com/KiraLinux/fbc94b6c986ea0323f516cb52f94d137
https://gist.github.com/KiraLinux/d116027e88a5b23a628e4fc22eb3ab41

**Comment by SirLyle** [comment] 2019-02-02 18:45
Google translate says:

> loads and crashes as soon as the Forgelin download hits
> 
> here is the event log

**Comment by SirLyle** [comment] 2019-02-02 22:11
Fix merged and uploaded to curse. Appears to have been due to java validating the classes referenced in methods when creating the sided proxy ... even when the sided proxy is never used.

**Closed as completed by SirLyle** 2019-02-02 22:11 UTC
Labels: bug

**Comment by TheSnowyChickens** [comment] 2019-02-02 22:36
@SirLyle Now with the new version (0.3.5), I can't start the client.

https://paste.dimdev.org/ufarihofew.mccrash

![grafik](https://user-images.githubusercontent.com/29357962/52170064-70300c80-2743-11e9-83be-2ee16cf3061f.png)

**Comment by SirLyle** [comment] 2019-02-02 23:35
That is the error reported in Issue #148, which I haven't been able to reproduce. It is seemingly unrelated to Issue #150.

Ex Nihilo + Applied Energistics is not enough to cause it so if you have any information to help narrow down a potential cross-mod (tri-mod?) interaction it would be appreciated.

**Comment by TheSnowyChickens** [comment] 2019-02-03 00:18
k.
I can try more later today, but now its time to sleep.

I will remove some mods and test some start conditions.

Edit: crashes are fixed, so I don't need to test. ^^
