### ISSUE TITLE
Mesh can't be placed in sieve

### ISSUE THREAD

**Issue by Rachmaninov13** [BloodWorkXGaming/ExNihiloCreatio#264] opened 2019-09-11 07:33 UTC
I'm playing E2:E with some extra mods, and for some reason, I can't place meshes into sieves. I've tried each type of mesh, no dice. Looked around on google and saw a few people who have had this issue, but not many, and it's not on the tracker. I don't know where to look to help troubleshoot, as I imagine it'll be nigh in possible to replicate on your end, but I'd love to help if I can.

**Comment by SirLyle** [comment] 2019-09-11 12:13
Please state what version of the mod you are using and upload the sieveregistry.json and cfg files.

**Comment by Rachmaninov13** [comment] 2019-09-11 14:38
I had the issue in 0.4.5, as well as in 0.4.6 (first thing I tried after restarting client and server was updating to the latest). Attached are the files in a zip.

[MeshIssue-sievereg_cfg.zip](https://github.com/BloodyMods/ExNihiloCreatio/files/3601321/MeshIssue-sievereg_cfg.zip)

**Comment by Rachmaninov13** [comment] 2019-09-11 18:05
After looking at the logs some more and changing the cfg, I think in this case it was the /dank/null integration. I have a newer version of that, and the logs had errors involving this mod and that with a call to p433word lib. When I disabled the integration in this cfg, the meshes placed again.

**Comment by SirLyle** [comment] 2019-09-11 21:47
Ah, it appears that /dank/null has had significant internal changes.

Thank you for reporting.

**Comment by SirLyle** [comment] 2019-09-12 21:21
Going to mark this as a dupe of Issue #265 (even though it was first) because @p455w0rd submitted a pull req for his issue.

**Closed as completed by SirLyle** 2019-09-12 21:21 UTC
Labels: bug, duplicate, mod compat
