### ISSUE TITLE
(wooden barrel)composting causing game to freeze up and not respond(1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [BloodWorkXGaming/ExNihiloCreatio#40] opened 2017-10-25 09:11 UTC
Forge:1.12.2-2515
exnihilo:1.12-0.1.5

log:
[latest.log.txt](https://github.com/BloodWorkXGaming/ExNihiloCreatio/files/1413968/latest.log.txt)

**Comment by SirLyle** [comment] 2017-10-27 23:50
What other mods are installed, is this a pack? Are you using default configs? What were you attempting to compost?

**Comment by SDUBZ** [comment] 2017-10-28 06:49
i was just composting  oak leaves into wooden barrel using hoppers
i will get mod list for you soon

**Comment by SirLyle** [comment] 2017-10-30 20:06
I haven't been able to reproduce the game freeze. That looks like a modpack, could you give me a link so I can see if they have made changes to the config. It seems that for some reason the barrel is not getting the recipe items correctly.

**Comment by SDUBZ** [comment] 2017-10-30 23:01
its a working progress pack im working on but weird things are happening that are hard to track down
[skycraft 2.5-1.0.zip](https://github.com/BloodWorkXGaming/ExNihiloCreatio/files/1429035/skycraft.2.5-1.0.zip)



most of the config is default apart from the json bit so i could tweak the drops etc

**Comment by SirLyle** [comment] 2017-10-31 00:21
So using your pack I got the error, but it didn't freeze or crash. Also it doesn't doesn't do it every time. Weird.

**Comment by SDUBZ** [comment] 2017-10-31 05:56
try hooking up wooden hoppers into wooden barrels feeding in oak leaves

**Comment by SirLyle** [comment] 2017-10-31 22:11
Oh I had interpreted you as meaning vanilla hoppers. Still not able to reliably produce the error using wooden hoppers (haven't seen the error since the first time). Can you replicate it every time? If so can you post a screenshot of the set up.

**Comment by SDUBZ** [comment] 2017-11-01 05:41
let me try doing setup again obviously i took it down from it crashing me

**Comment by SDUBZ** [comment] 2017-11-02 15:39
the setup i was using at the time http://puu.sh/yd8Sf/54774afce8.png

**Comment by SirLyle** [comment] 2017-11-02 23:14
I unfortunately still can not reproduce it. If you find a way to recreate it reliably let us know. It might be some weird interaction with one of the mods you have installed. If no new information or clues turn up in the next few months I will close this issue as can't reproduce.

Until then I am just going to leave this issue open in case anyone else can recreate it and wants to post more information.

**Comment by SDUBZ** [comment] 2017-11-04 04:03
yes i agree it might interaction until it happens again no clue what to tell you
will report back if it happens again and i find the culprit

**Closed** 2018-01-22 02:12 UTC
Labels: CouldNotReproduce, bug, help wanted
