### ISSUE TITLE
Can't use GregTech fluids in recipes

### ISSUE THREAD

**Issue by TheLimePixel** [BloodWorkXGaming/ExNihiloCreatio#92] opened 2018-06-15 13:10 UTC
Well, I'm making a GregTech-based skyblock pack and want End Stone to use something a bit more later in the game than Lava. I wanted it to use Nitration Mixture, but when I set the fluid name to "liquid.nitration_mixture" the recipe doesn't exist.

**Comment by BloodWorkXGaming** [comment] 2018-06-15 13:31
That really sounds like you are using the unlocalized name, it should be
something like 'gregtech:nitration_mixture'

EmosewaPixel <notifications@github.com> schrieb am Fr., 15. Juni 2018,
15:11:

**Comment by TheLimePixel** [comment] 2018-06-15 15:26
Nope, that's simply how GregTech generates its fluid names. I was thinking that perhaps it doesn't work because it starts with "liquid.".

**Comment by BloodWorkXGaming** [comment] 2018-06-15 15:32
Then you still might need the 'gregtech:liquid.whatever' as otherwise it
has no idea which mod the fluid is from

EmosewaPixel <notifications@github.com> schrieb am Fr., 15. Juni 2018,
17:26:

**Comment by TheLimePixel** [comment] 2018-06-15 15:44
In 1.12.2 mod names aren't used in fluid ids.

**Comment by BloodWorkXGaming** [comment] 2018-06-15 15:46
Mhhh, that's wierd then...
Will check it out in dev then when I find the time.

Greg isn't open source right?
Could've checked whether they are doing something wierd with their fluids.

EmosewaPixel <notifications@github.com> schrieb am Fr., 15. Juni 2018,
17:44:

**Comment by TheLimePixel** [comment] 2018-06-15 15:51
This is GregTech Community Edition: https://github.com/GregTechCE/GregTech

**Comment by TheLimePixel** [comment] 2018-06-15 15:52
Side-issue: its fluids show up white in Ex Nihilo Barrels. Might be related
![image](https://user-images.githubusercontent.com/25333164/41477526-d7a63b90-70c4-11e8-8aa4-22bbbfd03bdb.png)

**Comment by BloodWorkXGaming** [comment] 2018-06-15 16:20
Ye could possibly be connected, but I have no idea what might be the cause of either, if I find time this weekend I'll check it out more deeply

**Comment by BloodWorkXGaming** [comment] 2018-06-16 18:23
Apprently gregtech is doing wierd stuff with their fluids, as in not even Forge regonizes them as a fluid and adds a bucket variant of them.
![image](https://user-images.githubusercontent.com/8137062/41501344-f88934b4-71a2-11e8-8887-2696e45e6e89.png)
Those are all buckets, none of which are Gregtech.
In this case I can't really test it either as I have no idea how to obtain the fluids on a different way for quick testing purposes.
I suspect that those two issues have something to do with each other, but not sure.

**Comment by BloodWorkXGaming** [comment] 2018-06-16 18:57
![image](https://user-images.githubusercontent.com/8137062/41501588-ca13b064-71a7-11e8-9536-898939a6d6d8.png)
And regarding your colorless issue, can't really replicate, atleast helium has a color in the barrel for me

**Comment by BloodWorkXGaming** [comment] 2018-06-16 19:05
Welp, tested the recipes and that seems to work just fine as well:

https://gyazo.com/abda45cc791bf3f59cc4137836e04be2

**Comment by TheLimePixel** [comment] 2018-06-17 09:08
Huh, ok then. I'm away for a week so I can't really retest everything.

**Comment by BloodWorkXGaming** [comment] 2018-06-20 18:00
Closing this for now, if the problem is still there when test it again, just open it again or make a new issue and describe your steps closely so I can reproduce it

**Closed as completed by BloodWorkXGaming** 2018-06-20 18:00 UTC
