### ISSUE TITLE
Crash on a forge+paperspigot server.

### ISSUE THREAD

**Issue by CrystalCurtain** [BloodWorkXGaming/ExNihiloCreatio#245] opened 2019-07-02 04:27 UTC
Server crashed when startup.
and there is the crash-report.
Hope u can fix this.
THX!
(sorry for my Poor English)
 [ https://paste.ubuntu.com/p/TCyz7nPKqB/]( https://paste.ubuntu.com/p/TCyz7nPKqB/) 
(and The mean of Chinese:
server ticking loop.)

**Comment by CrystalCurtain** [comment] 2019-07-02 09:48
I have solved the problem by change the java runtime version....
But why could it worked?
?_?

**Comment by SirLyle** [comment] 2019-07-02 11:33
Without knowing what you changed from/to I can't speculate.

**Comment by SirLyle** [comment] 2019-08-05 22:26
Closing as the issue is solved and not enough information has been provided to determine if there was an issue to begin with.

**Closed as completed by SirLyle** 2019-08-05 22:26 UTC
Labels: Need More Information
